sudo: required

services:
- docker

dist: trusty
env:
  golang_version: "1.14.0"
  jenkins_version: "2.127"
  last_version: "latest"
  mysql_version: "5.7.31"
  openldap_version: "1.1.11"
  registry_ip: "10.110.27.103:6000"
stages:
  - pre-merge-requests
  - ui-test
  - api-test
  - report
install:
  - echo "install"
jobs:
  - stage: ui-test
    script:
      - echo "uitest script"
      - docker pull $registry_ip/board/dev_uibuilder:7.4
      - docker tag $registry_ip/board/dev_uibuilder:7.4 10.111.25.119/board/dev_uibuilder:7.4
      - docker-compose -f tests/docker-compose.uibuilder.test.yml up
      - code=$(docker inspect tests_uibuilder7.4_1 -f "{{.State.ExitCode}}"), exit $code
      - source /etc/profile
      - docker pull $registry_ip/library/golang:$golang_version
      - docker tag $registry_ip/library/golang:$golang_version golang:$golang_version
      - docker pull $registry_ip/library/registry:2.6.2        
      - docker tag $registry_ip/library/registry:2.6.2 registry:latest
      - docker pull $registry_ip/library/mysql:$mysql_version
      - docker tag $registry_ip/library/mysql:$mysql_version mysql:$mysql_version
      - docker pull $registry_ip/library/openldap:$openldap_version
      - docker tag $registry_ip/library/openldap:$openldap_version osixia/openldap:$openldap_version
      - docker pull $registry_ip/board/board-gogits:$last_version
      - docker tag $registry_ip/board/board-gogits:$last_version board-gogits:$last_version
      - docker pull $registry_ip/board/dev_jenkins:dev
      - docker tag $registry_ip/board/dev_jenkins:dev dev_jenkins:dev
      - docker pull $registry_ip/board/dev_gomail:dev
      - docker tag $registry_ip/board/dev_gomail:dev 10.111.25.119/board/dev_gomail:dev
      - docker pull $registry_ip/library/python:tavern2
      - docker tag $registry_ip/library/python:tavern2 python:tavern2
      - docker run --rm -v `pwd`:/data -v /etc/board/cert:/etc/board/cert python:tavern2 /data/make/prepare
      - source tests/env.cfg
      - cp tests/docker-compose.test.yml make/dev
      - cp tests/ldap_test.ldif make/dev
      - docker-compose -f make/dev/docker-compose.test.yml up -d
      - sh tests/hosts.gitlab.sh
      - docker run --rm -v $CI_PROJECT_DIR:/data/workspace/board/src/git/inspursoft/board -v /tmp:/tmp -w /data/workspace/board/src/git/inspursoft/board/tests --network host  -e GOPATH=/data/workspace/board golang:$golang_version bash -c "source env.cfg && source run.sh"
      - docker run --rm -v $CI_PROJECT_DIR/src:/go/src/git/inspursoft/board/src -v $CI_PROJECT_DIR/VERSION:/go/bin/VERSION -w /go/src/git/inspursoft/board/src/adminserver -e GO111MODULE=off golang:$golang_version go build -v -o /go/bin/adminserver
  - stage: api-test
    script:
      - echo "apitest script"

