sudo: required

services:
- docker

dist: trusty
env:
  golang_version: "1.14.0"
  jenkins_version: "2.127"
  last_version: "latest"
  mysql_version: "5.7.31"
  openldap_version: "1.1.11"
  registry_ip: "10.110.27.103:6000"
stages:
  - pre-merge-requests
  - ui-test
  - api-test
  - report
jobs:
  - stage: ui-test
    script:
      - echo "uitest script"
  - stage: api-test
    script:
      - echo "apitest script"
